In [1]:
#Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [4]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [7]:
np.searchsorted(arr ,34)

12

In [9]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
np.where(arr > 6)

(array([5, 8]),)

In [14]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [15]:
#Numpy - Byte Swapping.

In [16]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [18]:
#Numpy - Copies &Views.

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
a = np.copy(arr)

In [21]:
b = arr.view()

In [ ]:
b = arr

In [22]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
b[0] = 67

In [25]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [26]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [27]:
#Numpy - Matrix Library.

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5
        )

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
#Numpy - Linear Algebra

In [33]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [34]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [ ]:
np.dot()